### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by cchoi22915** [cu-ecen-aeld/final-project-cchoi22915#1]
**Tasks for Chris**

- [x]  Test GPIO Driver. 
 **DoD:** Integrated GPIO executable into the buildroot image which is flashed onto an uSD card and ran on the BeagleBone Black.  Verification of this executable is held through GPIO 48 or P9_23 with an LED anode connected to this pin and the cathode connected to P9_1.  This LED should blink with a period of two seconds and duty cycle of one second.  This will repeat indefinitely. 

- [x] Build PWM Driver based off of GPIO driver.
**DoD:** PWM .c and .h files created and initialization functions implemented (not yet tested)

- [ ] Test PWM Driver
**DoD:** An increasing PWM will be established to the led on GPIO 48 or P9_23 with an LED anode connected to this pin and the cathode connected to P9_1.  This LED should should have an increasing PWM over the span of 5 seconds and from 0 to 100% duty cycle and then reduce down to 0% with the next 5 seconds.  This will repeat indefinitely. 

**Blockers**
- Learn more about the PWM structure inside of the BBB and how to vary the timing of the wave based on incoming data.  This will be added to the next sprint for further investigation.

**Comment by cchoi22915** [comment]
Separated sprints from partner

**Comment by cchoi22915** [comment]
Was able to successfully verify GPIO running and LED blinking at 2 second periods with an on/off interval of 1 second
